algorithm_file: "algorithm.py"
evaluator_file: "evaluator.py"
brief_file: "BRIEF.md"
evolution_csv: "evolution.csv"
output_dir: ""

ideation_strategies:
  total_ideas: 3
  novel_exploration: 1
  hill_climbing: 1
  structural_mutation: 1
  crossover_hybrid: 0
  num_elites: 2

python_cmd: "python3"
auto_ideate: false

parallel:
  enabled: false

llm_cli:
  o3high: 'codex exec --profile o3high --dangerously-bypass-approvals-and-sandbox "{{PROMPT}}"'
  gpt5high: 'codex exec --profile gpt5high --dangerously-bypass-approvals-and-sandbox "{{PROMPT}}"'
  codex: 'codex exec --dangerously-bypass-approvals-and-sandbox "{{PROMPT}}"'
  gemini: 'gemini -y -p "{{PROMPT}}"'
  opus: 'claude --dangerously-skip-permissions --model opus -p "{{PROMPT}}"'
  sonnet: 'claude --dangerously-skip-permissions --model sonnet -p "{{PROMPT}}"'
  sonnet-think: 'claude --dangerously-skip-permissions --model sonnet -p "ultrathink\n\n{{PROMPT}}"'

  run: sonnet
  ideate: gemini sonnet-think sonnet-think gpt5high sonnet-think o3high
